### model
model_name_or_path: models/codeup_llama3_lora_sft_math

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj,o_proj,up_proj,down_proj
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05

### dataset
dataset: evol_codealpaca
template: llama3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: saves/codeup-llama3-8b/lora/sft-code
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
